[book]
authors = ["Eduardo Henrique Freire Machado"]
language = "pt-br"
src = "src"
title = "Guia do Analista de Dados da SEPLAN/RR"
description = "Guia do analista de dados da SEPLAN/RR, com foco em automatização e web scraping."

[output.html]
input-404 = "404.md"
# hash-files = true
# copy-fonts = true
